
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // CLI operations (migrate, db execute) run as the database owner via
    // DIRECT_URL; the app itself connects with the restricted DATABASE_URL role.
    //
    // Read the var directly instead of prisma's strict `env()` helper: the
    // build only runs `prisma generate`, which needs no connection, so a build
    // environment (e.g. a Vercel Preview) without DIRECT_URL must not hard-fail.
    // A live connection is only made by migrate/seed, which always set it.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
